ASSET_CONFIG = {
    'SHORT_WINDOW': 12,
    'LONG_WINDOW': 26,
    'SIGNAL_WINDOW': 9,
    'RSI_WINDOW': 14,
    'BOLLINGER_WINDOW': 20,
    'STD_DEV': 2,
    'SMOOTH_WINDOW': 3,
    'ADX_WINDOW': 14,
    'OBV_WINDOW': 14,
    'CCI_WINDOW': 20
}