version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ml-correlation-dashboard-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    container_name: ml-correlation-dashboard-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

networks:
  ml-correlation-dashboard-network:
    driver: bridge
